@startuml
object main.c
object failures.c
object ic.c
object osc.c
object port_config.c
object synchronization.c
object system_configuration.c
object timer.c
object uart.c
object config.h

main.c --> config.h
main.c --> osc.c
main.c --> timer.c
main.c --> ic.c
main.c --> uart.c
main.c --> port_config.c
main.c --> system_configuration.c
main.c --> synchronization.c
main.c --> failures.c

failures.c --> timer.c
failures.c --> synchronization.c

synchronization.c --> timer.c
synchronization.c --> uart.c
synchronization.c --> failures.c

system_configuration.c --> synchronization.c
system_configuration.c --> uart.c

uart.c --> system_configuration.c
uart.c --> failures.c
uart.c --> timer.c
@enduml