@startuml
scale 1.5

left to right direction
skinparam packageStyle rectangle
actor "Utilisateur" as u
actor "Middleware" as mid
rectangle Interface_utilisateur {
  usecase "Choisir le numéro de port COM" as COM
  usecase "Donner le ficher de configuration" as fiCo
  usecase "Configurer CRK" as CRK
  usecase "Configurer CAM" as CAM
  usecase "Choisir une erreur" as Err
  usecase "Réinitialiser CRK" as ReCRK
  usecase "Réinitialiser CAM" as ReCAM
  usecase "Quitter" as QUIT
  usecase "Afficher la liste des actions possible" as List
  usecase "Afficher le contenu du fichier de configuration" as ConfDis
  usecase "Afficher l'historique" as Hist
}
u --> CRK
u --> CAM
Err .> CRK:extends
Err .> CAM :extends
u --> COM
u --> fiCo
u --> ReCAM
u --> ReCRK
u --> QUIT
ConfDis <-- mid
List <-- mid
Hist <-- mid
@enduml
